### ISSUE TITLE
Possibility to apply template one step earlier

### ISSUE THREAD

**Issue by feustpat** [cschleiden/vsts-pr-templates#3]
When creating a new PR from a branch, the first screen already provides the possibility to write a Description. At this point, the user can't apply the markdown-template. 

![image](https://user-images.githubusercontent.com/19472984/36165245-35f6f53a-10ef-11e8-8616-3bedb61f1a2a.png)
* It would be great to have this possibility right here so that the user doesn't write a description first and then needs to update the description again with the provided template in the next step.
* Maybe there could even be a default template already pasted in the Description field (e.g. based on the branch path, `bug/*` would apply the bug.md template, `feature/*` the feature.md template etc.)
* If this is technically not possible, a hint on the first screen could indicate that templates can be applied in the next step.

**Comment by cschleiden** [comment]
@feustpat Thanks for the suggestion. I'd love to add that, but unfortunately VSTS does not provide any extension point on this page. I've talked to the team which owns this page, and they have plans to add one, but no ETA.
